[package]
name = "circuitlab-offline"
version = "0.1.0"
description = "Laboratório de circuitos digitais offline"
edition = "2021"

[lib]
name = "circuitlab_offline_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", default-features = false, features = ["wry", "x11", "custom-protocol"] }
circuitlab-engine = { path = "../engine" }
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
